name: Healthcheck

on:
  push:
      branches:
        - new-branch
  schedule:
    - cron: '* 20 * * *'

jobs:
  healthcheck:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v2
        with:
          url: https://pokemon-app22.herokuapp.com/
          follow-redirect: false
          max-attempts: 2
          retry-delay: 20s
